### ISSUE TITLE
Please release new npm version

### ISSUE THREAD

**Issue by wmertens** [hannoeru/esbuild-plugin-raw#226]
### Description

0.1.7 doesn't list latest esbuilds as peer deps

### Suggested solution

release 0.1.8 :)

### Validations

- [X] Follow the [Code of Conduct](https://github.com/hannoeru/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the docs.
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hannoeru** [comment]
v0.1.8 Released.
